edit task-related commands to utilise JCommander
AY2223S1-CS2103T-W10-4/tp pull request #114
Opened 2022-10-22 10:01 UTC by domoberzin

Legacy parsers are still left behind. Results in incorrect error messages if they are removed since add is a keyword for both modules and tasks.

Currently AddTaskCommand handles both deadline and tasks if JCommander is utilised.

2022-10-22 13:39 UTC, jontmy commented
The main parameter arg class error occurs because no `@Parameter` is defined for `-m`.

I think it's possible to add a boolean class attribute for the `-m` flag, then if both `-t` and `-m` are present (non-null) or both are absent, throw a `ParseException`.

This should eliminate the legacy parser for `add` entirely.

2022-10-25 00:19 UTC, domoberzin commented
Shorthand commands work as well, example usage below.
`add -t description -c code`
`add task -t description -c code`
`add -m -c code`
`add module -m -c code`

2022-10-25 04:16 UTC, domoberzin commented
As per @jontmy's suggestions, the commands are as follows:

`add mod -c <CODE>`
`add module -c <CODE>`
`add task <DESC> -c <CODE> [-d <DUE DATE>]`

Note that the position of flags still do not matter (i.e. -c and -d can be swapped around in task, will work the same)

2022-10-25 08:17 UTC, jontmy requested changes
Thanks for converting these to use JCommander! The commands with the format `add task -c CS2109S foo` and `add mod CS2105` don't seem to work though - it's not actually necessary for the main argument to immediately follow the scope, i.e. they can be anywhere in the command.

The implementation in this PR does some modifications of the tokens in `ModtrektParser` which wouldn't be needed if we use the main parameter functionality of JCommander:

[https://jcommander.org/#_main_parameter](
https://jcommander.org/#_main_parameter)

The changes should be fairly simple, removing `names = "-c"` and `names = "task"` from the `@Parameter`s and then reverting the changes to `ModtrektParser` should suffice.

2022-10-25 08:17 UTC, jontmy commented on src/main/java/modtrekt/logic/commands/AddCommand.java
>              + CliSyntax.PREFIX_MOD_CODE + "<CODE>";
Can this be removed? JCommander automatically generates usages from `@Parameter(description)`.

2022-10-25 08:17 UTC, jontmy commented on src/main/java/modtrekt/logic/commands/AddCommand.java
> +public class AddCommand extends Command {
I think this can be renamed to `AddModuleCommand` for consistency.

2022-10-25 08:17 UTC, jontmy commented on src/main/java/modtrekt/logic/parser/AddCommandParser.java
> +            return new AddCommand(code);
This file is unused and can be safely deleted.

2022-10-25 08:17 UTC, jontmy commented on src/main/java/modtrekt/logic/parser/AddTaskCommandParser.java
> +            return new AddDeadlineCommand(description, code, dueDate);
This file is unused and can be safely deleted.

2022-10-25 09:34 UTC, jontmy approved these changes

2022-10-25 09:40 UTC, merged