feat: add tasks while cd'd into module
AY2223S1-CS2103T-W10-4/tp pull request #117
Opened 2022-10-23 11:15 UTC by vvidday

closes #80 

Tried to use JCommander but decided to go with the old implementation halfway through since JCommander doesn't really have good support for conditionals AFAIK (since the same command word `add` will create either `AddCommand` or `AddTaskCommand` based on whether certain flags are present - didn't see a way to do this with JCommander). Not sure if this will be an issue @jontmy

2022-10-23 11:20 UTC, domoberzin commented
Actually, I wanted to suggest changing the adding module flag to something like `addm` or `mod`, so we can fully utilise JCommander. Else doing it with both tasks and modules using add doesn't seem easy. We should discuss it tomorrow, cause it seems very weird to have one parser doing half the commands and JCommander doing the rest

Also, JCommander doesnt display full error messages, unlike our legacy parser, so this might not fulfill the user story of displaying detailed error messages (UI/UX story 5)

2022-10-23 11:23 UTC, vvidday commented
Yeah definitely agree, I went with the legacy parser mainly because I couldn't figure out how to conditionally map to different classes based on the presence/absence of a parameter in JCommander. Separating the command words will solve this issue. Sure let's discuss this tomorrow in our meeting!

2022-10-23 11:25 UTC, domoberzin reviewed
LGTM, works fine for me with some light testing, but I think we should wait for a discussion between JCommander vs legacy parser before merging this

2022-10-23 12:09 UTC, jontmy commented
> Also, JCommander doesnt display full error messages, unlike our legacy parser, so this might not fulfill the user story of displaying detailed error messages (UI/UX story 5)

I've added implemented this in #115.

2022-10-25 14:41 UTC, jontmy commented on src/main/java/modtrekt/logic/commands/AddTaskCommand.java
> +    public static final String COMMAND_WORD = "add";
The command phrase is missing the scope - it should be `add task`.

2022-10-25 14:42 UTC, jontmy requested changes
Great work, tested and works, just missing the scope in the command.

2022-10-25 14:42 UTC, jontmy commented on src/main/java/modtrekt/logic/commands/AddTaskCommand.java
> +    public static final String COMMAND_WORD = "add";
The command phrase is missing the scope - it should be `add task`.

2022-10-25 16:02 UTC, vvidday commented on src/main/java/modtrekt/logic/commands/AddTaskCommand.java
> +    public static final String COMMAND_WORD = "add";
Great catch thanks!

2022-10-26 01:26 UTC, jontmy approved these changes
lgtm!

2022-10-26 01:26 UTC, merged